# Generated by Django 4.0.1 on 2022-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Уникальный слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ff0000', max_length=7, unique=True, verbose_name='Цвет в HEX'),
        ),
    ]
